# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchForLastDay():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_searchForLastDay(self):
    self.driver.get("https://ecampus.ius.edu.ba/")
    self.driver.set_window_size(1920, 1053)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Academic Calendar").click()
    self.vars["win1146"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1146"])
    self.driver.find_element(By.CSS_SELECTOR, ".gva-search-region > .icon").click()
    self.driver.find_element(By.ID, "edit-keys").click()
    self.driver.find_element(By.ID, "edit-keys").send_keys("last day of")
    self.driver.find_element(By.ID, "edit-keys").send_keys(Keys.ENTER)
  
